name: TTRPG Convert CLI
release:
  current-version: 3.1.5
  next-version: 3.1.5
  snapshot-version: 399-SNAPSHOT
build:
  artifact: ttrpg-convert-cli
jitpack:
  group: com.github.ebullient
  artifact: ttrpg-convert-cli
toggle: false
